### ISSUE TITLE
paramsForServer: unknown top level operator: $client

### ISSUE THREAD

**Issue by foxhound87** [feathers-plus/feathers-hooks-common#265]
Using `paramsForServer` hook on client for the find() method, 

`.find(paramsForServer({ query, ...params }))`

I get on server this error:

```
error:  MongoError: unknown top level operator: $client
    at Function.MongoError.create (/app/node_modules/mongodb-core/lib/error.js:31:11)
    at /app/node_modules/mongodb-core/lib/connection/pool.js:497:72
    at authenticateStragglers (/app/node_modules/mongodb-core/lib/connection/pool.js:443:16)
    at Connection.messageHandler (/app/node_modules/mongodb-core/lib/connection/pool.js:477:5)
    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:331:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:551:20)
```

server deps:
```
    "feathers": "^2.2.0",
    "feathers-authentication": "^1.2.7",
    "feathers-authentication-hooks": "^0.1.4",
    "feathers-authentication-jwt": "^0.3.2",
    "feathers-authentication-local": "^0.4.4",
    "feathers-authentication-management": "^1.0.0",
    "feathers-authentication-oauth2": "^0.2.5",
    "feathers-configuration": "^0.4.1",
    "feathers-errors": "^2.9.2",
    "feathers-hooks": "^2.0.2",
    "feathers-hooks-common": "^3.7.2",
    "feathers-mongoose": "^5.1.2",
    "feathers-rest": "^1.8.0",
    "feathers-socketio": "^2.0.0",
```

client deps:
```
    "feathers": "~2.1.7",
    "feathers-authentication-client": "~0.3.3",
    "feathers-authentication-management": "~1.0.0",
    "feathers-errors": "~2.8.2",
    "feathers-hooks": "~2.0.2",
    "feathers-hooks-common": "~3.7.3",
    "feathers-rest": "~1.8.0",
    "feathers-socketio": "~2.0.0",
```

**Comment by bertho-zero** [comment]
You have added the [paramsFromClient](https://docs.feathersjs.com/api/hooks-common.html#paramsfromclient) on the server ?

**Comment by foxhound87** [comment]
Yes I'm using it. Now I moved the `paramsFromClient` from specific services hooks to `app.hooks.js` (as `before.all`) and I randomly get `"$client" is read-only` error on the client.

To avoid this error I have to use this instead `paramsFromClient`:

```javascript
const query = {
  ...$query,
  $client: {
    ...params,
  },
};

return service(this.service).find({ query });

```

**Comment by eddyystop** [comment]
I expect you're using the common hooks incorrectly. Please post the code
you use for the service call on the client. Please also post the
app.hooks(ob) or service.hooks(obj) obj you use on the server.

**Comment by foxhound87** [comment]
on server:

> app.js
```javascript
const appHooks = require('./app.hooks');

...

app.hooks(appHooks); // as last call

...
```

> app.hooks.js
```javascript
const { paramsFromClient } = require('feathers-hooks-common');

module.exports = {
  before: {
    all: [paramsFromClient('action')],
    ...
  },
 ...
};
```

on client:

```javascript
import { paramsForServer } from 'feathers-hooks-common';

...

service('my-service').find(paramsForServer({ query, action: 'my-action' }));
```

**Comment by eddyystop** [comment]
Are you using a websocket or REST client?

Please run
```js
const { debug, paramsFromClient } = require('feathers-hooks-common');

module.exports = {
  before: {
    all: [debug(), paramsFromClient('action'), debug()],
    ...
  },
 ...
};
```
and post what `debug`s log to the console.

**Comment by foxhound87** [comment]
I'm using sockets, this is the log, but I think `"$client" is read-only` it's a client-side error, instead `MongoError: unknown top level operator: $client` was a server-side error.

I've also noticed that if I use Object.assign instead the spread operator in the [previous snippet](https://github.com/feathers-plus/feathers-hooks-common/issues/265#issuecomment-338153108), I always get `"$client" is read-only`.


```
type:before, method: create
data: { strategy: 'jwt',
  accessToken: 'eyJhbGciOiJIUzI1NiIsInR5cCI6ImFjY2VzcyIsInR5cGUiOiJhY2Nlc3MifQ.eyJ1c2VySWQiOiIyZmYyNjY0Mi04MzlhLTQ2ZDktYjc2Ny01OGVhZDg5NWE0OWYiLCJpYXQiOjE1MDg1MTY2MjgsImV4cCI6MTUwODYwMzAyOCwiYXVkIjoiaHR0cDovL21pbmRlc2sueHl6IiwiaXNzIjoiZmVhdGhlcnMiLCJzdWIiOiJhbm9ueW1vdXMifQ.Oh7Rlxcld1o2w_YcR4SU2Laqtx-6ziWi3SvgscdGRWg' }
query: {}
info: after: authentication - Method: create
* 
type:before, method: get
query: {}
* 
type:before, method: get
query: {}
* 
type:before, method: get
* 
type:before, method: get
* 
type:before, method: find
query: { userId: '2ff26642-839a-46d9-b767-58ead895a49f' }
* 
type:before, method: find
query: { userId: '2ff26642-839a-46d9-b767-58ead895a49f' }
info: after: users-profiles - Method: find
info: after: users - Method: get
* 
type:before, method: find
query: { userId: '2ff26642-839a-46d9-b767-58ead895a49f' }
* 
type:before, method: find
query: { userId: '2ff26642-839a-46d9-b767-58ead895a49f' }
info: after: users-profiles - Method: find
info: after: users - Method: get
```

**Comment by eddyystop** [comment]
There is no `query: { ..., $client: { ...} }` anywhere in those logs. This means none arrived from the client. I assume the problem is there.

Please replace your
```js
.find(paramsForServer({ query, ...params }))
``
with
``js
console.log('query=', query);
console.log('params=', params);
const test = paramsForServer({ query, ...params });
console.log('test=', test);
.find(test)
```
and post the logs.

**Comment by foxhound87** [comment]
```
query= {
  "$sort": {
    "issuedAt": 1,
    "requestedAt": -1
  },
  "$client": {
    "action": "all"
  },
  "$skip": 10
}

params= {
  "action": "all"
}

test= ERROR
```

```
Uncaught TypeError: Cannot assign to read only property 'action' of object '#<Object>'
    at params-for-server.js?819e199:25
    at Array.forEach (<anonymous>)
    at module.exports.exports.default (params-for-server.js?819e199:22)
```

It seems that cannot reassign the params if they are already assigned (if there's already the `$client` property in the query) If I do `delete query.$client;` before calling `paramsForServer` the , it's working but I'm still randomly getting: 


```
Cannot delete property '$client' of #<Object>
TypeError: Cannot delete property '$client' of #<Object>`
```

If I specify the `$client` prop inside the `query` obejct, without using `paramsForServer`, I don't get the error!

**Comment by eddyystop** [comment]
Just so I'm clear, are you saying that `paramsForServer` does not work if hook.params.query already has a $client property?

**Comment by eddyystop** [comment]
`paramsForServer` adds to an existing `context.params.query.$client` so that answers my question above.

The only explaination I can think of is that the preexisting `context.params.query.$client` is not an object, which would be a user error.

I have added a note to the Buzzard docs http://192.168.1.130:4000/v1/feathers-hooks-common/index.html#paramsforserver
